import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  screen: {
    height: "100%",
    width: "100%",
    justifyContent: "flex-end",
  },
  container: {
    position: "relative",
    backgroundColor: "#fff",
    height: 549,
    width: "100%",
    borderTopRightRadius: 25,
    borderTopLeftRadius: 25,
    paddingHorizontal: 16,
    paddingTop: 92,
    alignItems: "center",
  },
  avatarContainer: {
    flex: 1,
    flexDirection: "row",
    width: 132,
    height: 120,
    position: "absolute",
    top: -60,
  },
  avatarImg: {
    width: 120,
    height: "100%",
    backgroundColor: "#F6F6F6",
    borderRadius: 16,
    overflow: "hidden",
  },
  avatarBtn: {
    position: "relative",
    left: -12,
    top: 81,
    width: 25,
    height: 25,
  },
  text: {
    fontFamily: "Roboto-Black",
    fontSize: 30,
  },
  form: {
    marginTop: 32,
    width: "100%",
    alignItems: "center",
  },
  input: {
    width: "90%",
    height: 50,
    padding: 16,
    borderRadius: 8,
    backgroundColor: "#F6F6F6",
    borderWidth: 1,
    borderColor: "#E8E8E8",
    marginTop: 16,
    color: "#000",
  },
  singUpBtn: {
    width: "90%",
    height: 50,
    backgroundColor: "#FF6C00",
    borderRadius: 100,
    marginTop: 43,
    alignItems: "center",
    justifyContent: "center",
  },
  singUpText: {
    fontFamily: "Roboto-Black",
    fontSize: 16,
    color: "#fff",
  },
  imgBack: {
    flex: 1,
    justifyContent: "center",
    width: "100%",
    alignItems: "center",
  },
  singInText: {
    fontFamily: "Roboto-Black",
    fontSize: 16,
    color: "#1B4371",
    marginTop: 16,
  },
  passContainer: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  passBtn: {
    fontFamily: "Roboto-Black",
    position: "absolute",
    padding: 16,
    right: 16,
    bottom: 0,
    color: "#1B4371",
  },
});
