import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  screen: {
    height: "100%",
    width: "100%",
    paddingTop: 40,
  },
  container: {
    position: "relative",
    backgroundColor: "#fff",
    height: "100%",
    width: "100%",
    // paddingTop: 60,
    borderTopRightRadius: 25,
    borderTopLeftRadius: 25,
    paddingHorizontal: 16,
    // paddingTop: 92,
    alignItems: "center",
    paddingBottom: 20,
  },
  avatarContainer: {
    // flex: 1,
    flexDirection: "row",
    width: "95%",
    // height: 280,
    marginTop: 20,
    // position: "relative",
    // top: -60,
    // paddingBottom: 10,
    marginBottom: 10,
  },
  avatarImg: {
    width: "100%",
    height: 200,
    backgroundColor: "#F6F6F6",
    borderRadius: 16,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarBtn: {
    position: "absolute",
    left: -34,
    top: 160,
    width: 25,
    height: 25,
  },
  text: {
    fontFamily: "Roboto-Black",
    fontSize: 30,
  },
  form: {
    // marginTop: 10,
    width: "100%",
    alignItems: "center",
  },
  inputIng: {
    width: "95%",
    minHeight: 50,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: "#F6F6F6",
    borderWidth: 1,
    borderColor: "#E8E8E8",
    marginTop: 16,
    color: "#000",
  },
  inputCook: {
    flexGrow: 1,
    width: "95%",
    height: 120,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    textAlignVertical: "top",
    backgroundColor: "#F6F6F6",
    borderWidth: 1,
    borderColor: "#E8E8E8",
    marginTop: 16,
    color: "#000",
  },
  singUpBtn: {
    width: "95%",
    height: 50,
    backgroundColor: "#FF6C00",
    borderRadius: 100,
    marginTop: 43,
    alignItems: "center",
    justifyContent: "center",
  },
  singUpText: {
    fontFamily: "Roboto-Black",
    fontSize: 16,
    color: "#fff",
  },
  imgBack: {
    flex: 1,
    justifyContent: "center",
    width: "100%",
    alignItems: "center",
  },
  singInText: {
    fontFamily: "Roboto-Black",
    fontSize: 16,
    color: "#1B4371",
    marginTop: 16,
  },
  inputContainer: {
    width: "100%",
    alignItems: "center",
  },
});
